include:
  - board: seeeduino_xiao_ble
    shield: chipper_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: chipper_right rgbled_adapter

  - shield: settings_reset
    board: seeeduino_xiao_ble

